---
appName: "rest-sample"
description: "Rest Sample Application"
hostedZone: "midwesttape.com"
hostedZoneId: "Z3EGBUEG2M9ERS"
isRoute53: true
proxyServer: "apache"
solutionStackName: "64bit Amazon Linux 2017.09 v2.7.7 running Tomcat 8 Java 8"
